name: Header Frontend DEPLOY

on:
    push:
        branches: ["main"]

jobs:
    header_frontend:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: access to secretes / create .env file
              run: |
                echo "EXT_PUBLIC_KAKAO_MAP_API_KEY=${EXT_PUBLIC_KAKAO_MAP_API_KEY}" >> .env
              
              env:
                EXT_PUBLIC_KAKAO_MAP_API_KEY: ${{ secrets.NEXT_PUBLIC_KAKAO_MAP_API_KEY }}
            
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20.x
                cache: 'npm'

            - run: npm ci
            - run: npm run build --if-present
            - run: npm test

            - name: Docker build & push to prod
              run: |
                docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                docker build -t ${{ secrets.DOCKER_USERNAME }}/header-front-img:main .
                docker push ${{ secrets.DOCKER_USERNAME }}/header-front-img:main
            
            - name: Deploy to prod
              uses: appleboy/ssh-action@v1.0.3
            #   id: deploy-prod
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_PRIVATE_KEY }}
                envs: APPLICATION_PROPERTIES
                script: |
                    sudo docker stop header-front-container || true
                    sudo docker rm header-front-container || true
                    sudo docker pull ${{ secrets.DOCKER_USERNAME }}/header-front-img:main
                    sudo docker run -d \
                        --name header-front-container \
                        -p 3000:3000 \
                        ${{ secrets.DOCKER_USERNAME }}/header-front-img:main
                    sudo docker image prune -f

